# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crazyflie_multiagent.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 445)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../media/uoa_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(201, 405))
        self.frame_2.setMaximumSize(QtCore.QSize(201, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_connectall = QtWidgets.QPushButton(self.frame_2)
        self.btn_connectall.setGeometry(QtCore.QRect(10, 89, 84, 25))
        self.btn_connectall.setObjectName("btn_connectall")
        self.btn_exit = QtWidgets.QPushButton(self.frame_2)
        self.btn_exit.setGeometry(QtCore.QRect(10, 365, 80, 25))
        self.btn_exit.setAutoFillBackground(False)
        self.btn_exit.setObjectName("btn_exit")
        self.btn_scan = QtWidgets.QPushButton(self.frame_2)
        self.btn_scan.setGeometry(QtCore.QRect(10, 20, 80, 25))
        self.btn_scan.setObjectName("btn_scan")
        self.combobox_drone = QtWidgets.QComboBox(self.frame_2)
        self.combobox_drone.setGeometry(QtCore.QRect(100, 20, 86, 25))
        self.combobox_drone.setObjectName("combobox_drone")
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(471, 405))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.edit_yawrate = QtWidgets.QLineEdit(self.frame)
        self.edit_yawrate.setGeometry(QtCore.QRect(110, 158, 81, 25))
        self.edit_yawrate.setObjectName("edit_yawrate")
        self.edit_thrust = QtWidgets.QLineEdit(self.frame)
        self.edit_thrust.setGeometry(QtCore.QRect(110, 227, 81, 25))
        self.edit_thrust.setObjectName("edit_thrust")
        self.label_roll = QtWidgets.QLabel(self.frame)
        self.label_roll.setGeometry(QtCore.QRect(45, 25, 27, 21))
        self.label_roll.setObjectName("label_roll")
        self.label_pitch = QtWidgets.QLabel(self.frame)
        self.label_pitch.setGeometry(QtCore.QRect(45, 93, 35, 17))
        self.label_pitch.setObjectName("label_pitch")
        self.edit_pitch = QtWidgets.QLineEdit(self.frame)
        self.edit_pitch.setGeometry(QtCore.QRect(110, 89, 81, 25))
        self.edit_pitch.setObjectName("edit_pitch")
        self.label_thrust = QtWidgets.QLabel(self.frame)
        self.label_thrust.setGeometry(QtCore.QRect(45, 231, 45, 17))
        self.label_thrust.setObjectName("label_thrust")
        self.btn_snd_cmd = QtWidgets.QPushButton(self.frame)
        self.btn_snd_cmd.setGeometry(QtCore.QRect(71, 290, 121, 25))
        self.btn_snd_cmd.setObjectName("btn_snd_cmd")
        self.label_yawrate = QtWidgets.QLabel(self.frame)
        self.label_yawrate.setGeometry(QtCore.QRect(45, 162, 59, 17))
        self.label_yawrate.setObjectName("label_yawrate")
        self.edit_roll = QtWidgets.QLineEdit(self.frame)
        self.edit_roll.setGeometry(QtCore.QRect(110, 20, 81, 25))
        self.edit_roll.setObjectName("edit_roll")
        self.edit_x = QtWidgets.QLineEdit(self.frame)
        self.edit_x.setGeometry(QtCore.QRect(360, 20, 81, 25))
        self.edit_x.setObjectName("edit_x")
        self.edit_y = QtWidgets.QLineEdit(self.frame)
        self.edit_y.setGeometry(QtCore.QRect(360, 89, 81, 25))
        self.edit_y.setObjectName("edit_y")
        self.edit_z = QtWidgets.QLineEdit(self.frame)
        self.edit_z.setGeometry(QtCore.QRect(360, 158, 81, 25))
        self.edit_z.setObjectName("edit_z")
        self.edit_yaw = QtWidgets.QLineEdit(self.frame)
        self.edit_yaw.setGeometry(QtCore.QRect(360, 227, 81, 25))
        self.edit_yaw.setObjectName("edit_yaw")
        self.x_label = QtWidgets.QLabel(self.frame)
        self.x_label.setGeometry(QtCore.QRect(320, 25, 67, 17))
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(self.frame)
        self.y_label.setGeometry(QtCore.QRect(320, 93, 67, 17))
        self.y_label.setObjectName("y_label")
        self.z_label = QtWidgets.QLabel(self.frame)
        self.z_label.setGeometry(QtCore.QRect(320, 162, 67, 17))
        self.z_label.setObjectName("z_label")
        self.yaw_label = QtWidgets.QLabel(self.frame)
        self.yaw_label.setGeometry(QtCore.QRect(320, 231, 67, 17))
        self.yaw_label.setObjectName("yaw_label")
        self.btn_snd_pos_cmd = QtWidgets.QPushButton(self.frame)
        self.btn_snd_pos_cmd.setGeometry(QtCore.QRect(321, 290, 121, 25))
        self.btn_snd_pos_cmd.setObjectName("btn_snd_pos_cmd")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 696, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuInterface = QtWidgets.QMenu(self.menuBar)
        self.menuInterface.setObjectName("menuInterface")
        MainWindow.setMenuBar(self.menuBar)
        self.action3D_plotter = QtWidgets.QAction(MainWindow)
        self.action3D_plotter.setObjectName("action3D_plotter")
        self.action3D_visualiser = QtWidgets.QAction(MainWindow)
        self.action3D_visualiser.setObjectName("action3D_visualiser")
        self.menuInterface.addSeparator()
        self.menuInterface.addSeparator()
        self.menuInterface.addAction(self.action3D_visualiser)
        self.menuBar.addAction(self.menuInterface.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crazyflie Multiagent"))
        self.btn_connectall.setText(_translate("MainWindow", "Connect all"))
        self.btn_exit.setText(_translate("MainWindow", "EXIT"))
        self.btn_scan.setText(_translate("MainWindow", "Scan"))
        self.label_roll.setText(_translate("MainWindow", "Roll"))
        self.label_pitch.setText(_translate("MainWindow", "Pitch"))
        self.label_thrust.setText(_translate("MainWindow", "Thrust"))
        self.btn_snd_cmd.setText(_translate("MainWindow", "Send command"))
        self.label_yawrate.setText(_translate("MainWindow", "Yaw rate"))
        self.x_label.setText(_translate("MainWindow", "X"))
        self.y_label.setText(_translate("MainWindow", "Y"))
        self.z_label.setText(_translate("MainWindow", "Z"))
        self.yaw_label.setText(_translate("MainWindow", "Yaw"))
        self.btn_snd_pos_cmd.setText(_translate("MainWindow", "Send command"))
        self.menuInterface.setTitle(_translate("MainWindow", "Interface"))
        self.action3D_plotter.setText(_translate("MainWindow", "Simple Communication"))
        self.action3D_visualiser.setText(_translate("MainWindow", "3D visualiser"))
